### ISSUE TITLE
超分辨率图像无法保存

### ISSUE THREAD

**Issue by SocraSemicircle** [Xposed-Modules-Repo/io.github.yangyiyu08.taplusext#2]
![IMG_20230411_003229](https://user-images.githubusercontent.com/64609979/230947015-deabeaf8-56da-43d0-9e16-bae2b80c2617.jpg)
普通图像可保存，而如果选择超分辨率图像则无法保存，点击保存后无toast弹出，也没有保存文件

**Comment by buffcow** [comment]
这个需要设备底层支持的哈
