### ISSUE TITLE
系统更新后网页跳转失效

### ISSUE THREAD

**Issue by Ptilopsis01** [Xposed-Modules-Repo/io.github.yangyiyu08.taplusext#3]
如题，当前系统版本为MIUI14 v14.0.23.7.31.DEV，更新后发现传送门跳转网页的功能失效了，即能识别出链接并弹出侧栏，但点击后无反应
使用的默认浏览器是edge

**Comment by buffcow** [comment]
模块没问题，2.5.92版本的传送门由于miui开发者手抖把代码写抽风了，可以先回退传送门，或者等miui修复

**Comment by Ptilopsis01** [comment]
> 模块没问题，2.5.92版本的传送门由于miui开发者手抖把代码写抽风了，可以先回退传送门，或者等miui修复

ok明白了
